# Generated by Django 2.2 on 2021-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0004_auto_20210406_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='main_unit_price',
            field=models.FloatField(default=0.0, verbose_name='سعر الوحدة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.FloatField(default=0.0, verbose_name='سعر الوحدة المختارة'),
        ),
    ]
