# Generated by Django 2.2 on 2021-04-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='الصورة')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='تعليق')),
                ('url', models.URLField(blank=True, null=True, verbose_name='تحويل إلي')),
                ('disabled', models.BooleanField(default=False, verbose_name='تعطيل')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(blank=True, default='#000000', max_length=7, null=True, verbose_name='اللون الاساسي')),
                ('primary_text_color', models.CharField(blank=True, default='#ffffff', max_length=7, null=True, verbose_name='لون النص في اللون الاساسي')),
                ('title', models.CharField(default='ON-Link', max_length=128, verbose_name='اسم الموقع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='الشعار')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='اسم الصفحة')),
                ('content', models.TextField(verbose_name='محتوي الصفحة')),
                ('add_to_menu', models.BooleanField(default=False, verbose_name='إضافة للقائمة الرئيسية')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Website.Page', verbose_name='تحت صفحة')),
                ('tags', models.ManyToManyField(blank=True, to='Website.Tag', verbose_name='الكلمات الدلالية')),
            ],
        ),
    ]
