# Generated by Django 2.2 on 2021-04-04 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='الاسم بالكامل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='الصورة الشخصية')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='الهاتف')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='العنوان')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني')),
                ('qualification', models.CharField(blank=True, max_length=128, null=True, verbose_name='المؤهل')),
                ('id_type', models.IntegerField(blank=True, choices=[(1, 'بطاقة رقم قومي'), (2, 'جواز سفر')], null=True, verbose_name='نوع تحقيق الشخصية')),
                ('national_id', models.CharField(blank=True, max_length=28, null=True, verbose_name='رقم تحقيق الشخصية')),
                ('id_issued_from', models.CharField(blank=True, max_length=128, null=True, verbose_name='جهة إصدار تحقيق الشخصية')),
                ('settlement_end_date', models.DateField(blank=True, null=True, verbose_name='انتهاء الاقامة/تحقيق الشخصية')),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='الراتب')),
                ('over', models.FloatField(blank=True, null=True, verbose_name='الحافز')),
                ('insurance_start', models.DateField(blank=True, null=True, verbose_name='تاريخ التأمين')),
                ('insurance_end', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('insurance_cost', models.FloatField(blank=True, null=True, verbose_name='تكلفة التأمينات')),
                ('finger_print_id', models.IntegerField(blank=True, null=True, verbose_name='الرقم علي جهاز البصمة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء العقد')),
                ('religion', models.IntegerField(blank=True, choices=[(1, 'مسلم'), (2, 'مسيحي'), (3, 'يهودي')], null=True, verbose_name='الديانة')),
                ('military_state', models.IntegerField(blank=True, choices=[(1, 'معفي نهائي'), (2, 'معفي مؤقت'), (3, 'أتم فترة التجنيد')], null=True, verbose_name='موقف التجنيد')),
                ('relationship', models.IntegerField(blank=True, choices=[(1, 'أعزب'), (2, 'خاطب'), (3, 'متزوج'), (4, 'مطلق'), (5, 'أرمل')], null=True, verbose_name='الحالة الاجتماعية')),
                ('rest_credit', models.IntegerField(blank=True, null=True, verbose_name='رصيد الإجازات')),
                ('weekly_rest_days', models.IntegerField(blank=True, null=True, verbose_name='أيام الاجازة الاسبوعية')),
                ('monthly_rest_days', models.IntegerField(blank=True, null=True, verbose_name='أيام الاجازة الشهرية')),
                ('yearly_rest_days', models.IntegerField(blank=True, null=True, verbose_name='أيام الاجازة السنوية')),
                ('employee_type', models.IntegerField(blank=True, choices=[(1, 'متقدم لوظيفة'), (2, 'موظف مؤقت'), (3, 'موظف دائم')], null=True, verbose_name='نوع الموظف')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='المسمي الوظيفي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='المهام الوظيفية')),
                ('available_job', models.BooleanField(default=False, verbose_name='توجد وظائف متاحة؟')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='الملف')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Employee', verbose_name='الموظف')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.JobTitle', verbose_name='المسمي الوظيفي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حساب البرنامج'),
        ),
    ]
