# Generated by Django 2.2 on 2021-04-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_jobtitle_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
    ]
