# Generated by Django 2.2 on 2021-04-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'خزينة'), (2, 'حساب بنكي'), (3, 'حساب عهدة'), (4, 'حساب سلف رواتب')], verbose_name='النوع')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('no', models.CharField(blank=True, max_length=128, null=True, verbose_name='رقم الحساب')),
                ('initial_balance', models.FloatField(default=0, verbose_name='الرصيد الافتتاحي')),
                ('deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_treasuires', to='Branches.Branch', verbose_name='الفرع المرتبط')),
            ],
        ),
    ]
