# Generated by Django 2.2 on 2021-04-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasuries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='type',
            field=models.IntegerField(choices=[(1, 'خزينة'), (2, 'حساب بنكي'), (3, 'حساب عهدة'), (4, 'حساب سلف رواتب'), (5, 'حساب فيزا')], verbose_name='النوع'),
        ),
    ]
