# Generated by Django 2.2 on 2021-04-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasuries', '0006_paymentmachines_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmachines',
            name='discount_percentage',
            field=models.FloatField(default=0, verbose_name='نسبة الخصم'),
        ),
    ]
