# Generated by Django 2.2 on 2021-04-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='التليفون')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'permissions': (('add_branch', 'إضافة فرع'), ('edit_branch', 'تعديل فرع'), ('delete_branch', 'حذف فرع'), ('access_branch_menu', 'الدخول علي قائمة الفروع')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='اسم المخزن')),
                ('deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Branches.Branch', verbose_name='الفرع')),
            ],
            options={
                'permissions': (('add_warehouse', 'إضافة مخزن'), ('edit_warehouse', 'تعديل مخزن'), ('delete_warehouse', 'حذف مخزن'), ('access_warehouse_menu', 'الدخول علي قائمة المخازن')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BranchWarehouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Branches.Branch', verbose_name='الفرع')),
                ('main_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_warehouse_set', to='Branches.Warehouse', verbose_name='المخزن الرئيسي')),
                ('sub_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_warehouse_set', to='Branches.Warehouse', verbose_name='المخزن الفرعي')),
            ],
        ),
    ]
