# Generated by Django 2.2 on 2021-04-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0002_paymentmachines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMachines',
        ),
    ]
