# Generated by Django 2.2 on 2021-04-04 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='التاريخ')),
                ('task_type', models.IntegerField(choices=[(1, 'خاص'), (2, 'عام')], default=1, verbose_name='النوع')),
                ('comment', models.TextField(null=True, verbose_name='ملاحظات')),
                ('done', models.BooleanField(default=False, verbose_name='تم')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_tasks', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.Customer', verbose_name='متعلقة بـ')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRespond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(null=True, verbose_name='الرد')),
                ('done_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.Task', verbose_name='الموعد')),
            ],
        ),
    ]
