# Generated by Django 2.2 on 2021-04-04 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Customers', '__first__'),
        ('InvoicesMaged', '0001_initial'),
        ('Branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Treasuries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magedwarehousetransactions',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='magedwarehousetransactions',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Branches.Warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='magedtreasurytransactions',
            name='treasury',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Treasuries.Treasury', verbose_name='الخزينة'),
        ),
        migrations.AddField(
            model_name='magedinvoiceitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoicesMaged.MagedInvoice', verbose_name='الفاتورة'),
        ),
        migrations.AddField(
            model_name='magedinvoiceitems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='magedinvoiceitems',
            name='unit_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='magedinvoice',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Branches.Branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='magedinvoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.Customer', verbose_name='العميل / المورد'),
        ),
        migrations.AddField(
            model_name='magedinvoice',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='magedinvoice',
            name='main_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_warehouse_invoice', to='Branches.Warehouse', verbose_name='المخزن الرئيسي'),
        ),
        migrations.AddField(
            model_name='magedinvoice',
            name='sub_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_warehouse_invoice', to='Branches.Warehouse', verbose_name='المخزن الفرعي'),
        ),
        migrations.AddField(
            model_name='magedinvoice',
            name='treasury',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Treasuries.Treasury', verbose_name='الخزينة'),
        ),
        migrations.AddField(
            model_name='invoicebasesetting',
            name='default_customer_in_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_customer_in_sales', to='Customers.Customer', verbose_name='العميل الافتراضي لفاتورة المبيعات'),
        ),
    ]
