# Generated by Django 2.2 on 2021-04-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_auto_20210404_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Technicians.Technician', verbose_name='الفنين'),
        ),
    ]
