# Generated by Django 2.2 on 2021-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_auto_20210405_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='opration',
            field=models.IntegerField(choices=[(1, '-'), (2, '+')], default=1, verbose_name='العملية'),
        ),
        migrations.AddField(
            model_name='category',
            name='percentage',
            field=models.FloatField(default=0.0, verbose_name='النسبة'),
        ),
    ]
