# Generated by Django 2.2 on 2021-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20210415_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='administrator',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='المسئول'),
        ),
        migrations.AddField(
            model_name='customer',
            name='purchase_invoices_comments',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات بفاتوره المشتريات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='الموبايل'),
        ),
    ]
