# Generated by Django 2.2 on 2021-04-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_auto_20210418_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Products_status',
            field=models.CharField(choices=[('red', 'احمر'), ('yellow', 'اصفر'), ('green', 'اخضر')], max_length=50, verbose_name='حالة المنتجات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payments_status',
            field=models.CharField(choices=[('red', 'احمر'), ('yellow', 'اصفر'), ('green', 'اخضر')], max_length=50, verbose_name='حالة الدفعات'),
        ),
    ]
