# Generated by Django 2.2 on 2021-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_auto_20210418_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Products_status',
            field=models.CharField(blank=True, choices=[('#FF0000', 'احمر'), ('#fff400', 'اصفر'), ('#00c33e', 'اخضر')], max_length=50, null=True, verbose_name='حالة المنتجات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payments_status',
            field=models.CharField(blank=True, choices=[('#FF0000', 'احمر'), ('#fff400', 'اصفر'), ('#00c33e', 'اخضر')], max_length=50, null=True, verbose_name='حالة الدفعات'),
        ),
    ]
