# Generated by Django 2.2 on 2021-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_auto_20210418_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payments_status',
            field=models.CharField(blank=True, choices=[('#FF0000', 'احمر'), ('#fff400', 'اصفر'), ('#00c33e', 'اخضر')], default='#00c33e', max_length=50, null=True, verbose_name='حالة الدفعات'),
        ),
    ]
