# Generated by Django 2.2 on 2021-04-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0011_auto_20210418_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='opration',
        ),
        migrations.RemoveField(
            model_name='category',
            name='percentage',
        ),
    ]
