# Generated by Django 2.2 on 2021-04-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.TextField(default=1, verbose_name='المحتوي'),
            preserve_default=False,
        ),
    ]
