# Generated by Django 2.2 on 2021-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('primary_color', models.CharField(max_length=12)),
                ('secondary_color', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ModulesSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_module', models.BooleanField(default=False, verbose_name='المشروعات')),
                ('invoices_module', models.BooleanField(default=False, verbose_name='الفواتير')),
                ('calendar_module', models.BooleanField(default=False, verbose_name='الأجندة')),
                ('maintenance_module', models.BooleanField(default=False, verbose_name='الصيانة')),
                ('website_module', models.BooleanField(default=False, verbose_name='الموقع')),
                ('expiration', models.DateField(default='2020-01-01', verbose_name='تاريخ إنتهاء الترخيص')),
                ('support_expiration', models.DateField(default='2020-01-01', verbose_name='تاريخ إنتهاء الدعم')),
                ('host_expiration', models.DateField(default='2020-01-01', verbose_name='تاريخ إنتهاء الإستضافة')),
            ],
        ),
    ]
