# Generated by Django 2.2 on 2021-04-21 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_lastseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastseen',
            name='user',
        ),
        migrations.AddField(
            model_name='lastseen',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='online_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
