# Generated by Django 2.2 on 2021-04-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20210421_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastseen',
            old_name='user_id',
            new_name='user',
        ),
    ]
