# Generated by Django 2.2 on 2021-04-04 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
            options={
                'permissions': (('add_brand', 'إضافة براند'), ('edit_brand', 'تعديل براند'), ('delete_brand', 'حذف براند'), ('access_brand_menu', 'الدخول علي قائمة البراندات')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
            options={
                'permissions': (('add_main_category', 'إضافة تصنيف رئيسي للمنتجات'), ('edit_main_category', 'تعديل تصنيف رئيسي للمنتجات'), ('delete_main_category', 'حذف تصنيف رئيسي للمنتجات'), ('access_main_category_menu', 'الدخول علي التصنيف الرئيسية للمنتجات')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
            options={
                'permissions': (('add_manufacture', 'إضافة جهة مصنعة للمنتجات'), ('edit_manufacture', 'تعديل جهة مصنعة للمنتجات'), ('delete_manufacture', 'حذف جهة مصنعة للمنتجات'), ('access_manufacture_menu', 'الدخول علي قائمة الجهات المصنعة')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PricesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField(choices=[(1, 'منتج عادي'), (2, 'منتج مجمع'), (3, 'خدمة')], default=1, verbose_name='النوع')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('sell_price', models.FloatField(default=0.0, verbose_name='سعر البيع الرئيسي')),
                ('cost_price', models.FloatField(default=0.0, verbose_name='سعر التكلفة الرئيسي')),
                ('purchase_price', models.FloatField(default=0.0, verbose_name='سعر الشراء الرئيسي')),
                ('initial_value', models.FloatField(default=0.0, verbose_name='القيمة الافتتاحية')),
                ('max_sell', models.FloatField(blank=True, null=True, verbose_name='حد الصرف')),
                ('full_stock', models.FloatField(blank=True, null=True, verbose_name='حد الطلب')),
                ('critical_stock', models.FloatField(default=1, verbose_name='الرصيد الحرج للفرع الواحد')),
                ('critical_stock_overall', models.FloatField(default=1, verbose_name='الرصيد الحرج لجميع الفروع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sell_price_last_update', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث للسعر')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Brand', verbose_name='البراند')),
                ('initial_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Branches.Branch', verbose_name='الفرع الافتتاحي')),
            ],
            options={
                'ordering': ['id'],
                'permissions': (('add_product', 'إضافة منتج'), ('edit_product', 'تعديل منتج'), ('delete_product', 'حذف منتج'), ('view_purchase_price', 'مشاهدة سعر الشراء'), ('view_cost_price', 'مشاهدة سعر التكلفة'), ('access_product_menu', 'الدخول علي قائمة المنتجات')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.MainCategory', verbose_name='المجموعة الرئيسية')),
            ],
            options={
                'permissions': (('add_sub_category', 'إضافة تصنيف فرعي للمنتجات'), ('edit_sub_category', 'تعديل تصنيف فرعي للمنتجات'), ('delete_sub_category', 'حذف تصنيف فرعي للمنتجات'), ('access_sub_category_menu', 'الدخول علي التصنيف الفرعية للمنتجات')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_quantity', models.FloatField(default=1, verbose_name='الكمية')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
                ('unit_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_from', to='Products.Unit', verbose_name='من وحدة')),
                ('unit_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_name', to='Products.Unit', verbose_name='الوحدة')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='السعر')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('inactive', models.BooleanField(default=False, verbose_name='تعطيل الشريحة')),
                ('customer_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.Category', verbose_name='الشريحة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Product', verbose_name='اسم المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='ProductActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True, verbose_name='وقت الحركة')),
                ('action_type', models.CharField(max_length=128, verbose_name='نوع الحركة')),
                ('action_name', models.CharField(max_length=128, verbose_name='اسم الحركة')),
                ('action_from', models.CharField(max_length=128, verbose_name='تغيير من')),
                ('action_to', models.CharField(max_length=128, verbose_name='تغيير الي')),
                ('action_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الوظف')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Product', verbose_name='اسم المنتج')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='main_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_unit', to='Products.Unit', verbose_name='الوحدة الاساسية'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Manufacture', verbose_name='الجهة المصنعة'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.PricesList', verbose_name='اسم قائمة الأسعار'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.SubCategory', verbose_name='المجموعة'),
        ),
        migrations.CreateModel(
            name='GroupedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0, verbose_name='الكمية')),
                ('contain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='Products.Product', verbose_name='المنتج')),
                ('grouped_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_item', to='Products.Product', verbose_name='المنتج المجمع')),
            ],
        ),
    ]
