# Generated by Django 2.2 on 2021-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_auto_20210404_1921'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='critical_stock_overall',
            new_name='critical_stock_for_all_branches',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='critical_stock',
            new_name='critical_stock_for_one_branch',
        ),
        migrations.AddField(
            model_name='product',
            name='accountant_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات للمحاسب'),
        ),
        migrations.AddField(
            model_name='product',
            name='critical_stock_for_one_warehouse',
            field=models.FloatField(default=1, verbose_name='الرصيد الحرج للمخزن الواحد'),
        ),
        migrations.AddField(
            model_name='product',
            name='forbid_customer_group',
            field=models.ManyToManyField(to='Customers.Category', verbose_name='إيقاف البيع لشرائح معينة'),
        ),
        migrations.AddField(
            model_name='product',
            name='forbid_for_reverse',
            field=models.BooleanField(default=False, verbose_name='ممنوع من المرتجع'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات للورقة المطبوعة'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_man_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات للبائع'),
        ),
    ]
