# Generated by Django 2.2 on 2021-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210404_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='forbid_customer_group',
            field=models.ManyToManyField(null=True, to='Customers.Category', verbose_name='إيقاف البيع لشرائح معينة'),
        ),
    ]
