# Generated by Django 2.2 on 2021-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210406_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='forbid_customer_group',
            field=models.ManyToManyField(blank=True, null=True, to='Customers.Category', verbose_name='إيقاف البيع لشرائح معينة'),
        ),
    ]
