# Generated by Django 2.2 on 2021-04-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210406_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_unit', to='Products.Unit', verbose_name='الوحدة الاساسية'),
        ),
    ]
