# Generated by Django 2.2 on 2021-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210412_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price_factor',
            field=models.FloatField(default=0.0, verbose_name='معامل سعر الشراء الرئيسي'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price_factor',
            field=models.FloatField(default=0.0, verbose_name='معامل سعر البيع الرئيسي '),
        ),
    ]
