# Generated by Django 2.2 on 2021-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210413_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprices',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='الترتيب'),
        ),
    ]
