# Generated by Django 2.2 on 2021-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_productprices_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprices',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='الترتيب'),
        ),
    ]
