# Generated by Django 2.2 on 2021-04-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20210413_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_price_factor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price_factor',
        ),
        migrations.AddField(
            model_name='productunit',
            name='purchase_price_factor',
            field=models.FloatField(default=0.0, verbose_name='معامل سعر الشراء'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='sell_price_factor',
            field=models.FloatField(default=0.0, verbose_name='معامل سعر البيع'),
        ),
    ]
