# Generated by Django 2.2 on 2021-04-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_auto_20210415_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='forbid_customer_group',
            field=models.ManyToManyField(blank=True, null=True, to='Customers.Customer', verbose_name='إيقاف البيع لشرائح معينة'),
        ),
    ]
