# Generated by Django 2.2 on 2021-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_auto_20210418_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price_new',
            field=models.FloatField(default=0.0, verbose_name='سعر شراء للجديد'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price_new_activation',
            field=models.BooleanField(default=False, verbose_name='تنشيط سعر الشراء الجديد'),
        ),
    ]
