# Generated by Django 2.2 on 2021-04-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_auto_20210418_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price_new_comment',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات سعر شراء جديد'),
        ),
    ]
