# Generated by Django 2.2 on 2021-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_product_purchase_price_new_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='Products.Brand', verbose_name='الكتالوج'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='Products.SubCategory', verbose_name='مجموعه البدائل '),
        ),
    ]
