# Generated by Django 2.2 on 2021-04-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_product_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.CharField(choices=[('#FF0000', 'احمر'), ('#fff400', 'اصفر'), ('#00c33e', 'اخضر')], default='#FFFFFF', max_length=50, verbose_name='درجه البونص'),
        ),
    ]
