# Generated by Django 2.2 on 2021-04-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_auto_20210418_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.CharField(choices=[('#FFFFFF', ''), ('#FF0000', 'احمر'), ('#fff400', 'اصفر'), ('#00c33e', 'اخضر')], default='#FFFFFF', max_length=50, verbose_name='درجه البونص'),
        ),
    ]
