# Generated by Django 2.2 on 2021-04-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_customerprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceslist',
            name='opration',
            field=models.IntegerField(choices=[(1, '-'), (2, '+')], default=1, verbose_name='العملية'),
        ),
        migrations.AddField(
            model_name='priceslist',
            name='percentage',
            field=models.FloatField(default=0.0, verbose_name='النسبة'),
        ),
    ]
