# Generated by Django 2.2 on 2021-04-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_auto_20210419_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprices',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='سعر القائمه'),
        ),
    ]
