# Generated by Django 2.2 on 2021-04-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_remove_customerprices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprices',
            name='discount',
            field=models.FloatField(default=0.0, verbose_name='النسبة'),
        ),
        migrations.AddField(
            model_name='customerprices',
            name='opration',
            field=models.IntegerField(choices=[(1, '-'), (2, '+')], default=1, verbose_name='العملية'),
        ),
    ]
