# Generated by Django 2.2 on 2021-04-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_auto_20210419_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceslist',
            name='opration',
        ),
        migrations.RemoveField(
            model_name='priceslist',
            name='percentage',
        ),
    ]
